# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: service.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\rservice.proto\x12\x0bnodeService\"3\n\tNodeEvent\x12\n\n\x02id\x18\x01 \x01(\x05\x12\x0c\n\x04type\x18\x02 \x01(\t\x12\x0c\n\x04term\x18\x03 \x01(\x05\x32P\n\x11NodeCommunication\x12;\n\tSendEvent\x12\x16.nodeService.NodeEvent\x1a\x16.nodeService.NodeEventb\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'service_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _NODEEVENT._serialized_start=30
  _NODEEVENT._serialized_end=81
  _NODECOMMUNICATION._serialized_start=83
  _NODECOMMUNICATION._serialized_end=163
# @@protoc_insertion_point(module_scope)
